config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'static_pages#home'
  get 'users/new', to: 'users#new', as: 'user_new'
  post 'users/new', to: 'users#create'
  get 'users/error', to: 'users#error'
  get 'users/:id', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
  end

  def create
    @users = User.create(
      username: params[:username],
      email: params[:email],
      bio: params[:bio]
    )

    if @users.errors.any?
      redirect_to('/users/error')
    else
      redirect_to("/users/#{@users.username}")
    end
  end

  def show
    @users = User.find_by(username:params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackEnd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Bienvenu sur ma page d'accueil</h1>

<p> Pour créer un utilisateur  <%= link_to "c'est par ici" , user_new_path %>
</p>

app/views/user/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<p>Bienvenue dans la création d'utilisateurs ! </p>
<body>
  <form method="post">
    Username:<br>
    <input type="text" name="username"><br>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<br>
  Email:<br>
  <input type="text" name="email"><br>

  <br>

    <p> <label for ="bio"> Ecrire votre bioligraphie</label><br>
    <textarea name="bio" id="decrire"> </textarea>

<br>
  <input type="submit" value ="Envoyer">
</form>
</body>

</html>

app/views/users/error.html.erb
<h1> error </h1>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<p>Bienvenue dans la création d'utilisateurs ! </p>

<body>
  <form method="post">
    Username:<br>
    <input type="text" name="username"><br>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <br>
    <form method="post">
      Email:<br>
      <input type="text" name="email"><br>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <br>

      <p> <label for ="bio"> Ecrire votre biographie</label><br>
        <textarea name="bio" id="decrire"> </textarea>

        <br>
        <input type="submit" value ="Envoyer">
      </form>
    </body>
    </html>

app/views/users/show.html.erb
<p>Bienvenue username ! Voici ta bio trop cool : bio ! </p>
<%=@users.username%>
<br>
<%=@users.email%>
<br>
<%=@users.bio%>